displayName: Authorization on paths
type: middleware

import: github.com/nilskohrs/pathauth

summary: 'Authorization on paths'

testData:
  cookies:
    source:
      type: "header" # optional, default = header
      name: "X-Forwarded-User"
      delimiter: "," # the delimiter is useful if the input header has multiple values, for example roles. We can then check if the request meets any of the values from the headers. optional
    authorization:
      - path: ".*/admin/.*"
        method: # http methods which this rule matches with. optional, default = all methods
          - POST
        allowed:
          - "update-only-user"
          - "admin-user"
        priority: 0 # the priority, in ascending number order, in which the authorization rule will be checked. optional, default = 0
      - path: ".*/admin/.*"
        allowed: "admin-user"
        priority: 1
