displayName: "Pathauth: Authorization by headers"
type: middleware

import: github.com/nilskohrs/pathauth

summary: "Pathauth is a middleware plugin to apply more detailed authorization to multiple endpoints at once. This plugin was developed to work well together with Traefik Enterprise OpenId Connection Authentication Middleware and thomseddon traefik-forward-auth"

testData:
  source:
    type: "header" # optional, default = header
    name: "X-Forwarded-User"
    delimiter: "," # the delimiter is useful if the input header has multiple values, for example roles. We can then check if the request meets any of the values from the headers. optional
  authorization:
    - path: ".*/admin/.*"
      host: "^example.com$"
      method: # http methods which this rule matches with. optional, default = all methods
        - POST
      allowed:
        - "update-only-user"
        - "admin-user"
      priority: 0 # the priority, in ascending number order, in which the authorization rule will be checked. optional, default = 0
    - path: ".*/admin/.*"
      host: "^example.com$"
      allowed: "admin-user"
      priority: 1
