displayName: "Pathauth: Authorization by headers"
type: middleware

import: github.com/nilskohrs/pathauth

summary: "Pathauth is a middleware plugin to apply more detailed authorization to multiple endpoints at once. This plugin was developed to work well together with Traefik Enterprise OpenId Connection Authentication Middleware and thomseddon traefik-forward-auth"

testData:
  source:
    type: "header" # optional, default = header
    name: "X-Forwarded-User"
    delimiter: "," # the delimiter is useful if the input header has multiple values, for example roles. We can then check if the request meets any of the values from the headers. optional
  authorization:
    - match: "PathPrefix(`/{.*}/admin`)" # Works the same as Traefik's HTTP Router Rule
      allowed:
        - "admin"
      priority: 1 # Works the same as Traefik's HTTP Router Rule priority
    - match: "Path(`/{.*}/admin/health`)"
      priority: 2
      allowed:
        - "monitoring"
